// components/Footer.tsx
const Footer = () => (
  <footer className="bg-secondary border-t border-primary">
    <div className="container mx-auto px-6 md:px-16 py-8 md:py-12 flex flex-col md:flex-row">
      <div className="mb-5 md:mb-0 md:mr-10 leading-none font-semibold text-lg">
        © Aman Harwara
      </div>
      <ul
        className="md:mt-0 mb-5 md:mb-0 md:mr-10 flex flex-row md:flex-col"
        aria-label="List of social media links"
      >
        <li className="mr-8 md:mr-0 md:mb-6 hover:underline">
          <a
            href="https://github.com/amanharwara"
            target="_blank"
            rel="noreferrer noopener"
          >
            GitHub
          </a>
        </li>
        <li className="mr-8 md:mr-0 md:mb-6 hover:underline">
          <a
            href="https://gitlab.com/amanharwara"
            target="_blank"
            rel="noreferrer noopener"
          >
            GitLab
          </a>
        </li>
        <li className="hover:underline">
          <a
            href="https://mastodon.social/@amanharwara"
            target="_blank"
            rel="noreferrer noopener"
          >
            Mastodon
          </a>
        </li>
      </ul>
      <ul
        className="md:mt-0 flex flex-row md:flex-col"
        aria-label="List of music-related links"
      >
        <li className="mr-8 md:mr-0 md:mb-6 hover:underline">
          <a
            href="https://amanharwara.bandcamp.com/"
            target="_blank"
            rel="noreferrer noopener"
          >
            Bandcamp
          </a>
        </li>
        <li className="mr-8 md:mr-0 md:mb-6 hover:underline">
          <a
            href="https://open.spotify.com/artist/0oS1w3XT067ttzelzj67b6"
            target="_blank"
            rel="noreferrer noopener"
          >
            Spotify
          </a>
        </li>
        <li className="hover:underline">
          <a
            href="https://www.youtube.com/channel/UCHk6MIPQhtZf6zFS_FrDHKg"
            target="_blank"
            rel="noreferrer noopener"
          >
            YouTube
          </a>
        </li>
      </ul>
    </div>
  </footer>
);

export default Footer;

// components/Footer.vue
<template>
  <footer>
    <div class="section-container flex">
      <div class="copyright">(c) Aman Harwara</div>
      <div class="social column">
        <div class="column-title">Social</div>
        <div class="links">
          <a
            target="_blank"
            rel="noopener noreferrer"
            href="https://mastodon.social/@amanharwara"
            >Mastodon</a
          >
          <a
            target="_blank"
            rel="noopener noreferrer"
            href="https://instagram.com/aman.harwara"
            >Instagram</a
          >
          <a
            target="_blank"
            rel="noopener noreferrer"
            href="https://github.com/amanharwara"
            >GitHub</a
          >
          <a
            target="_blank"
            rel="noopener noreferrer"
            href="https://gitlab.com/amanharwara"
            >GitLab</a
          >
        </div>
      </div>
      <div class="music column">
        <div class="column-title">Music</div>
        <div class="links">
          <a
            target="_blank"
            rel="noopener noreferrer"
            href="https://amanharwara.bandcamp.com"
            >Bandcamp</a
          >
          <a
            target="_blank"
            rel="noopener noreferrer"
            href="https://open.spotify.com/artist/0oS1w3XT067ttzelzj67b6"
            >Spotify</a
          >
          <a
            target="_blank"
            rel="noopener noreferrer"
            href="https://music.apple.com/us/artist/aman-harwara/1516521816"
            >Apple Music</a
          >
          <a
            target="_blank"
            rel="noopener noreferrer"
            href="https://www.youtube.com/channel/UCHk6MIPQhtZf6zFS_FrDHKg"
            >YouTube</a
          >
        </div>
      </div>
    </div>
  </footer>
</template>

<style lang="scss" scoped>
footer {
  padding: 1.5rem;
  background: #080808;
  color: #fff;
}
.copyright {
  margin-bottom: 1rem;
}
.links {
  display: flex;
  flex-flow: column nowrap;
}
.column {
  display: inline-block;
}
.social {
  margin-right: 3rem;
}
.column-title {
  margin-bottom: 0.5rem;
  font-weight: bold;
  font-size: 1.25rem;
}
a {
  color: #fff;
  &:hover {
    text-decoration: none;
  }
  &:not(:last-child) {
    margin-bottom: 1rem;
  }
}
@media screen and (min-width: 768px) {
  footer {
    padding: 3rem 0;
  }
  .column-title {
    margin-top: 0;
  }
  .social {
    margin: 0 5rem;
  }
}
</style>
