// components/portfolio/WorkSection.jsx
/** @jsx jsx */
import { css, jsx } from "@emotion/core";
import Section from "./Section";
import projects from "../../data/projects";
import ProjectCard from "./ProjectCard";
import ProjectExtended from "./ProjectExtended";

const breakpoints = [576, 1024, 1280, 1370];
const media_queries = breakpoints.map((bp) => `@media (max-width: ${bp}px)`);

const WorkSectionEllipse = ({ ...props }) => (
  <div
    css={css`
      background: #3352c0;
      border-radius: 50%;
      position: absolute;
      z-index: -2;
    `}
    {...props}
  ></div>
);

const WorkSectionClickHandler = (e) => {
  if (e.target.closest(".project-card")) {
    let project_card = e.target.closest(".project-card");

    // Hide project cards
    document.querySelector(".projects-grid").style.display = "none";
    document.querySelector(".selected-project-container").style.display = "";

    // Display extended project info
    document.getElementById(project_card.dataset.id).classList.add("visible");
    document.getElementById("work-section").scrollIntoView();
  } else if (e.target.closest(".close-button")) {
    e.target.closest(".project-extended").classList.remove("visible");
    document.querySelector(".projects-grid").style.display = "";
    document.getElementById("work-section").scrollIntoView();
  }
};

const WorkSectionKeyDownHanlder = (e) => {
  if (e.key === "Enter") {
    if (document.activeElement.matches(".project-card")) {
      // Hide project cards
      document.querySelector(".projects-grid").style.display = "none";
      document.querySelector(".selected-project-container").style.display = "";

      // Display extended project info
      document
        .getElementById(document.activeElement.dataset.id)
        .classList.add("visible");
      document.getElementById("work-section").scrollIntoView();
    }

    if (document.activeElement.matches(".close-button")) {
      document.querySelector(".visible").classList.remove("visible");
      document.querySelector(".projects-grid").style.display = "";
    }
  }
};

const WorkSection = () => (
  <Section
    id="work-section"
    style={{ background: "#0c257e", color: "#fff" }}
    onClick={WorkSectionClickHandler}
    onKeyDown={WorkSectionKeyDownHanlder}
    css={css`
      ${media_queries[1]} {
        min-height: 100%;
      }
    `}
  >
    <h1>Work</h1>
    <div
      className="projects-grid"
      css={css`
        display: flex;
        justify-content: space-between;
        width: 100%;
        height: 78vh;

        ${media_queries[1]} {
          flex-direction: column;
          height: auto;
        }
      `}
    >
      {projects.map((project) => (
        <ProjectCard {...project} key={`card-${project.title}`} />
      ))}
    </div>
    <div
      className="selected-project-container"
      style={{ display: "none" }}
      css={css`
        width: 100%;
        height: 78vh;
        position: relative;

        ${media_queries[1]} {
          height: auto;
          position: absolute;
          top: 0;
          left: 0;
          width: 100%;
          height: 100%;
          box-sizing: border-box;
        }
      `}
    >
      {projects.map((project) => (
        <ProjectExtended {...project} key={`extended-${project.title}`} />
      ))}
    </div>
    <WorkSectionEllipse
      css={css`
        width: 17vw;
        height: 17vw;
        top: -6.5%;
        left: -6%;
        background: linear-gradient(
          136.21deg,
          #3352c0 20.58%,
          rgba(51, 82, 192, 0) 88.57%
        );
      `}
    />
    <WorkSectionEllipse
      css={css`
        width: 16vw;
        height: 16vw;
        top: 10%;
        right: -6%;
        background: linear-gradient(
          213.99deg,
          #3352c0 18.26%,
          rgba(51, 82, 192, 0) 85.56%
        );
      `}
    />
    <WorkSectionEllipse
      css={css`
        width: 16vw;
        height: 16vw;
        bottom: -15%;
        left: 15%;
        background: linear-gradient(
          55.85deg,
          #3352c0 20.35%,
          rgba(51, 82, 192, 0) 82.87%
        );
      `}
    />
  </Section>
);

export default WorkSection;

// components/WorkSection.vue
<template>
  <section id="work-section">
    <div class="section-container">
      <h1>Work</h1>
      <div class="projects-container">
        <!-- <ProjectCard
          v-for="project in projects"
          :key="project.id"
          :project="project"
          type="work"
        /> -->
        <div
          class="project"
          v-for="project in projects"
          :key="project.id"
          :style="`background: ${project.color}`"
        >
          <NuxtLink :to="`/project/${project.id}`" class="project-link">
            <h2>{{ project.title }}</h2>
            <p>{{ project.shortDescription }}</p>
            <div class="overlay"></div>
          </NuxtLink>
        </div>
      </div>
      <p class="open-source-work">
        My open-source projects can be found on
        <a
          href="https://github.com/amanharwara/"
          target="_blank"
          rel="noopener noreferrer"
          >GitHub</a
        >
        and
        <a
          href="https://gitlab.com/amanharwara/"
          target="_blank"
          rel="noopener noreferrer"
          >GitLab</a
        >.
      </p>
    </div>
  </section>
</template>

<script lang="ts">
import Vue from 'vue'
import projects from '@/data/projects'

export default Vue.extend({
  data: () => {
    return {
      projects,
    }
  },
})
</script>

<style lang="scss" scoped>
section {
  padding: 1.5rem;
}
h1 {
  font-size: 2rem;
  margin-top: 0;
}
.projects-container > :not(:last-child) {
  margin-bottom: 1.5rem;
}
.overlay {
  width: 100%;
  height: 100%;
  position: absolute;
  top: 0;
  left: 0;
  background: rgba(0, 0, 0, 0.5);
  opacity: 0;
  z-index: -1;
  transition: opacity 0.15s;
}
.project-link {
  display: flex;
  flex-flow: column;
  justify-content: center;
  padding: 2rem;
  width: 100%;
  height: 100%;
  position: relative;
  text-decoration: none;
  color: #fff;

  h2 {
    font-size: 2.65rem;
    transition: font-size 0.15s;
  }

  &:hover {
    .overlay {
      opacity: 1;
    }
  }
}
@media screen and (min-width: 768px) {
  section {
    padding: 3rem 0;
  }
  h1 {
    font-size: 3rem;
    margin-top: 0;
    text-align: left;
  }
  .projects-container {
    display: flex;
    flex-flow: row wrap;
    & > :first-child,
    & > :nth-child(3n + 1) {
      flex: 1 100%;

      h2 {
        font-size: 3rem;
      }

      p {
        max-width: 50%;
      }

      &:hover {
        h2 {
          font-size: 3.35rem;
        }
      }
    }
  }
  .project-link {
    padding: 5rem;
    text-align: center;
    align-items: center;

    &:hover {
      h2 {
        font-size: 3rem;
      }
    }
  }
  .project {
    flex: 1 50%;
    min-height: 75vh;
    margin: 0 !important;
    z-index: 0;
  }
  p {
    margin: 2rem 0;
  }
}
</style>
