// components/Footer.vue
<template>
  <footer class="section">
    <div class="copyright">(c) Aman Harwara</div>
    <div class="social column">
      <h3>Social</h3>
      <div class="links">
        <a
          target="_blank"
          rel="noopener noreferrer"
          href="https://mastodon.social/@amanharwara"
          >Mastodon</a
        >
        <a
          target="_blank"
          rel="noopener noreferrer"
          href="https://instagram.com/aman.harwara"
          >Instagram</a
        >
        <a
          target="_blank"
          rel="noopener noreferrer"
          href="https://github.com/amanharwara"
          >GitHub</a
        >
        <a
          target="_blank"
          rel="noopener noreferrer"
          href="https://gitlab.com/amanharwara"
          >GitLab</a
        >
      </div>
    </div>
    <div class="music column">
      <h3>Music</h3>
      <div class="links">
        <a
          target="_blank"
          rel="noopener noreferrer"
          href="https://amanharwara.bandcamp.com"
          >Bandcamp</a
        >
        <a
          target="_blank"
          rel="noopener noreferrer"
          href="https://open.spotify.com/artist/0oS1w3XT067ttzelzj67b6"
          >Spotify</a
        >
        <a
          target="_blank"
          rel="noopener noreferrer"
          href="https://music.apple.com/us/artist/aman-harwara/1516521816"
          >Apple Music</a
        >
        <a
          target="_blank"
          rel="noopener noreferrer"
          href="https://www.youtube.com/channel/UCHk6MIPQhtZf6zFS_FrDHKg"
          >YouTube</a
        >
      </div>
    </div>
  </footer>
</template>

<style lang="scss" scoped>
footer {
  background: #070707;
  color: #fff;
  display: flex;
  align-items: flex-start;

  & > :not(:last-child) {
    margin-right: 4.5vw;
  }
}

.column,
.links {
  display: flex;
  flex-direction: column;
}

a {
  color: #fff;
  text-decoration: none;
  font-size: 1.35vw;
  font-weight: 300;

  &:not(:last-child) {
    margin-bottom: 0.5vw;
  }

  &:hover {
    text-decoration: underline;
  }
}

h3,
.copyright {
  margin: 0 0 0.75vw 0;
  font-size: 1.35vw;
}

@media screen and (max-width: 800px) {
  footer {
    display: block;
    padding: 1.75rem;

    h3,
    .copyright {
      font-size: 1.25rem;
    }

    .copyright {
      margin-bottom: 1.5rem;
    }

    .column {
      display: inline-flex;

      &:last-child {
        margin-left: 2rem !important;
      }

      *:not(:last-child) {
        margin-bottom: 1rem;
      }
    }

    a {
      font-size: 1.15rem;
    }
  }
}
</style>

// components/blog/Footer.tsx
/** @jsx jsx */
import { css, jsx } from "@emotion/core";
import Github from "@/icons/GitHub";
import Instagram from "@/icons/Instagram";
import Mastodon from "@/icons/Mastodon";

const breakpoints = [576, 1024, 1280, 1370];
const media_queries = breakpoints.map((bp) => `@media (max-width: ${bp}px)`);

const FooterLink = ({ children, href, ...props }) => (
  <a
    className="footer-link"
    href={href}
    target="_blank"
    rel="noopener noreferrer"
    {...props}
    css={css`
      display: flex;
      fill: #fff;
      font-size: 1.75vw;
      margin-right: 1vw;

      ${media_queries[1]} {
        font-size: 1.25rem;
        margin-right: 0.75rem;
      }
    `}
  >
    {children}
  </a>
);

const Footer = () => (
  <footer
    css={css`
      background: #131313;
      color: #fff;
      padding: 0.75vw 3vw;
      font-size: 1.3vw;
      display: flex;
      align-items: center;
      justify-content: space-between;

      ${media_queries[1]} {
        padding: 1rem 1.25rem;
        font-size: 1rem;
      }
    `}
  >
    <div className="left">(c) 2020 Aman Harwara</div>
    <div
      className="right"
      css={css`
        display: flex;
      `}
    >
      <FooterLink href="https://github.com/amanharwara">{Github}</FooterLink>
      <FooterLink href="https://mastodon.social/@amanharwara">
        {Mastodon}
      </FooterLink>
      <FooterLink
        href="https://instagram.com/aman.harwara"
        style={{ marginRight: "0" }}
      >
        {Instagram}
      </FooterLink>
    </div>
  </footer>
);

export default Footer;
