// components/NavBar.vue
<template>
  <nav class="navbar">
    <label for="hamburger">&#9776;</label>
    <input type="checkbox" id="hamburger" />
    <div class="links">
      <a :href="item.link" v-for="item in menu" :key="item.label">
        {{ item.label }}
      </a>
    </div>
  </nav>
</template>

<script lang="ts">
import Vue from 'vue'
export default Vue.extend({
  props: {
    menu: {
      type: Array as () => NavMenu,
      required: true,
    },
  },
})
</script>

<style lang="scss" scoped>
input {
  display: none;
}

label {
  font-size: 1.75rem;
}

input:checked ~ .links {
  display: flex;
  flex-flow: column nowrap;
  position: absolute;
  top: 100%;
  left: 0;
  width: 100%;
  z-index: 3;
  padding: 0;
}

a {
  text-align: center;
  font-size: 1rem;
  border-top: 1px solid rgba(44, 44, 44, 0.6);
  transition: background 0.15s;
  background: #fff;
  user-select: none;
  text-decoration: none;
  color: #000;
  padding: 1.1rem;

  &:hover {
    background: #1b1b1b;
    color: #fff;
  }

  &:last-child {
    border-bottom: 1px solid rgba(44, 44, 44, 0.6);
  }
}

.links {
  display: none;
  list-style: none;
  margin: 0;
}

@media screen and (min-width: 768px) {
  label {
    display: none;
  }
  .links {
    display: flex;
  }
  a {
    font-size: 1.2rem;
    border: 0 !important;
    padding: 0;
    background: transparent;
    cursor: pointer;

    &:hover {
      background: initial;
      color: initial;
      text-decoration: underline;
    }

    &:not(:last-child) {
      margin-right: 1.5rem;
    }
  }
  @supports (width: max(1rem, 1vw)) {
    a {
      font-size: max(1.2rem, 0.8vw);
      &:not(:last-child) {
        margin-right: max(1.5rem, 1.25vw);
      }
    }
  }
}
</style>

// components/portfolio/NavBar.tsx
/** @jsx jsx */
import { css, jsx } from "@emotion/core";
import Logo from "./Logo";

const breakpoints = [576, 1024, 1280, 1370];
const min_media_queries = breakpoints.map(
  (bp) => `@media (min-width: ${bp}px)`
);
const max_media_queries = breakpoints.map(
  (bp) => `@media (max-width: ${bp}px)`
);

const MenuItem = ({ children, link, ...props }) => (
  <li
    {...props}
    css={css`
      color: #fff;
      font-weight: 300;
      font-size: 1.8vw;
      margin-right: 1.2vw;
      user-select: none;

      &.active {
        font-weight: 800;
      }

      ${max_media_queries[1]} {
        font-size: 1.35rem;
      }
    `}
  >
    <a
      href={link}
      css={css`
        color: inherit;
        text-decoration: none;
        &:hover {
          text-decoration: underline;
        }
      `}
    >
      {children}
    </a>
  </li>
);

const NavBar = () => (
  <div
    css={css`
      width: 100%;
      box-sizing: border-box;
      display: flex;
      align-items: center;
      justify-content: space-between;
      position: relative;
      ${max_media_queries[1]} {
        margin-bottom: 2.5rem;
      }
    `}
  >
    <div
      className="logo"
      css={css`
        display: flex;
        font-weight: 800;
        font-size: 2vw;
        ${max_media_queries[1]} {
          font-size: 1.5rem;
        }
      `}
    >
      AMANHARWARA
    </div>
    <nav
      css={css`
        & label,
        #hamburger {
          display: none;
        }

        ${max_media_queries[1]} {
          & label {
            display: flex;
            color: white;
            font-style: normal;
            font-size: 1.5rem;
          }

          .menu {
            display: none;
          }
          & input:checked ~ .menu {
            display: flex;
            width: 100%;
            position: absolute;
            left: 0;
            top: 100%;
            background: #3352c0;
            justify-content: center;
            padding: 1rem;
            box-sizing: border-box;

            li {
              margin-right: 1rem;
            }
          }
        }
      `}
    >
      <label htmlFor="hamburger">&#9776;</label>
      <input type="checkbox" id="hamburger" />
      <ul
        className="menu"
        css={css`
          display: flex;
          list-style: none;
          padding: 0;
          margin: 0;
        `}
      >
        <MenuItem link="/" className="active">
          HOME
        </MenuItem>
        <MenuItem link="#work-section">WORK</MenuItem>
        <MenuItem link="#contact">CONTACT</MenuItem>
      </ul>
    </nav>
  </div>
);

export default NavBar;
